name: "PROD DEPLOY"

on:
  push:
    branches:
      - master

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    uses: ./.github/workflows/terraform.yml
    with:
      environment: prod
      aws-assume-role-arn: "arn:aws:iam::699475933877:role/github-actions-mayconjovan-pipeline"
      aws-region: "us-east-1"
      aws-statefile-s3-bucket: "mayconjovan-us-east-1-terraform-statefile"
      aws-lock-dynamodb-table: "mayconjovan-us-east-1-terraform-lock"

